config/settings.yml

Moving openshift related events to the providers-openshift repo from the main repo.
cc: @cben @simon3z

Moving events from main repo settings to provider-openshift repo

---

app/models/manageiq/providers/openshift/container_manager/refresh_parser.rb

Adding a static mapping between openshift entities to miq entities.

Add mapping for Container entities

---

manageiq-providers-openshift.gemspec

Issue #14
cc @simon3z @cben @moolitayer

Add dependency on manageiq-providers-kubernetes

---

config/settings.yml

Issue #3 
Moving openshift related settings from core repo to openshift repo settings file.
cc @cben @simon3z

Moving openshift related settings

---

app/models/manageiq/providers/openshift/container_manager/refresh_parser.rb
spec/models/manageiq/providers/openshift/container_manager/refresh_parser_spec.rb

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1461785
Openshift issue: https://github.com/openshift/origin/issues/14730

Fix parsing for Container Template without objects

---

spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb

Following https://github.com/ManageIQ/manageiq/pull/15251,
similar to
https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/55
@miq-bot add-label test
@simon3z @moolitayer @zakiva please review, tiny fix for red master

Update refresher_spec for soft delete

---

.rspec
.rspec_ci
bin/setup
bin/update
config/settings.yml
lib/tasks_private/spec.rake
spec/spec_helper.rb

ran the generator again with
```bash
bundle exec rails g provider <name> --path ../
```
these are the changes.

run provider generator to sync changes from core

---

spec/models/manageiq/providers/openshift/container_manager/refresh_parser_spec.rb
spec/spec_helper.rb

Openshift followup to https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/58
@miq-bot add-labels refactoring, test

Let ROS recurse_over_arrays, matching kubeclient

---

app/models/manageiq/providers/openshift/container_manager.rb
app/models/manageiq/providers/openshift/container_manager/inventory_collector_worker.rb
app/models/manageiq/providers/openshift/container_manager/inventory_collector_worker/runner.rb
config/settings.yml

Depends on: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/129

Add an Openshift InventoryCollectorWorker

---

config/settings.yml

Depends on: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/154

Add a setting to only send DELETED notices

---

CHANGELOG.md

[Changelog] Update master for Gaprindashvili updates

---

CHANGELOG.md

[Changelog] Adding missing release date

---

app/models/manageiq/providers/openshift/container_manager/refresher.rb

Remove useless EmsRefresherMixin removed in https://github.com/ManageIQ/manageiq/pull/17472

Remove useless EmsRefresherMixin

---

app/models/manageiq/providers/openshift/inventory/persister/target_collection.rb

Depends on:
Switch to proper targeted refresh

Switch to proper targeted refresh

---

lib/manageiq/providers/openshift/engine.rb

See ManageIQ/manageiq-ui-classic#4496 for primary motivation.

Add plugin display name

---

app/models/manageiq/providers/openshift/inventory/persister.rb

Move ManagerRefresh::Inventory to ManageIQ::Providers::Inventory

Move Inventory to ManageIQ::Providers

---

spec/models/manageiq/providers/openshift/container_manager/targeted_refresh/targeted_refresh_spec.rb

Move ManagerRefresh to InventoryRefresh
Depends on:

Move ManagerRefresh to InventoryRefresh

---

app/models/manageiq/providers/openshift/container_manager/refresh_worker/runner.rb

Depends on https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/287

Updates for streaming service catalog

---

app/models/manageiq/providers/openshift/container_manager/service_instance.rb
spec/models/manageiq/providers/openshift/container_manager/refresher_inventory_object_spec.rb

Specs for refreshing service instances

---

spec/factories/container_image.rb
spec/factories/ext_management_system.rb
spec/factories/openshift_template.rb
spec/models/manageiq/providers/openshift/container_manager/container_image_spec.rb
spec/models/manageiq/providers/openshift/container_manager/container_template_spec.rb
spec/models/manageiq/providers/openshift/container_manager/orchestration_stack_spec.rb
spec/models/manageiq/providers/openshift/container_manager/refresher_inventory_object_spec.rb
spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
spec/models/manageiq/providers/openshift/container_manager/targeted_refresh/targeted_refresh_spec.rb
spec/models/manageiq/providers/openshift/container_manager_spec.rb

This PR is a followup to ManageIQ/manageiq#18279 where we're updating FactoryGirl to FactoryBot.

Change FactoryGirl to FactoryBot

---

lib/manageiq/providers/openshift/engine.rb

Change plugin common methods to class methods

Change plugin common methods to class methods

---

spec/vcr_cassettes/manageiq/providers/openshift/container_manager/test_objects_record.sh
spec/vcr_cassettes/manageiq/providers/openshift/container_manager/test_objects_template.yml

Fix a few issues with generating test_objects for specs

Fix test_objects generation

---

app/models/manageiq/providers/openshift/container_manager/event_catcher.rb
app/models/manageiq/providers/openshift/container_manager/metrics_collector_worker.rb
app/models/manageiq/providers/openshift/container_manager/refresh_worker.rb
app/models/manageiq/providers/openshift/monitoring_manager/event_catcher.rb

Requires https://github.com/ManageIQ/manageiq/pull/19516

Rely on the default implementation of .ems_class

---

app/models/manageiq/providers/openshift/container_manager.rb
spec/models/manageiq/providers/openshift/container_manager/refresher_inventory_object_spec.rb
spec/models/manageiq/providers/openshift/container_manager/targeted_refresh/targeted_refresh_spec.rb

just what it says on the tin
@miq-bot add_label cleanup
@miq-bot assign @agrare
Adam, did I miss anything on this targeted_refresh_spec?

remove inventory object refresh

---

app/models/manageiq/providers/openshift/inventory/collector/container_manager.rb
app/models/manageiq/providers/openshift/inventory/parser/container_manager.rb

Assorted graph refresh cleanups

---

app/models/manageiq/providers/openshift/container_manager.rb
spec/models/manageiq/providers/openshift/container_manager_spec.rb

Cross Repo Tests: https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/106
Core PR: https://github.com/ManageIQ/manageiq/pull/20039

Make Provider Catalog Types Pluggable

---

app/models/manageiq/providers/openshift/container_manager_mixin.rb

The project and route names changed on v4 as well as hawkular is no longer supported.
Fixes https://github.com/ManageIQ/manageiq-providers-openshift/issues/173

Add metrics/alerts hostname detection on OCP v4

---

app/models/manageiq/providers/openshift/container_manager.rb
app/models/manageiq/providers/openshift/container_manager/container_template.rb

Add checks for supported features to Container Templates
Depends on: https://github.com/ManageIQ/manageiq/pull/20314

Add supports feature checks to ContainerTemplate#instantiate

---

.codeclimate.yml
.gitignore
.rubocop.yml
.rubocop_cc.yml
.travis.yml
README.md
Rakefile
bin/ci/after_script
lib/manageiq/providers/openshift/engine.rb
lib/tasks/README.md
lib/tasks_private/spec.rake
manageiq-providers-openshift.gemspec
spec/spec_helper.rb

Plugin Generator Updates

---

.codeclimate.yml
.rubocop.yml
.rubocop_cc.yml
manageiq-providers-openshift.gemspec

Depends on: https://github.com/ManageIQ/miq_bot/pull/506

Switch to manageiq-style

---

config/settings.yml

@agrare Please review.  This can be merged indepently of the core removal PR.

Move hawkular settings from core settings

---

app/models/manageiq/providers/openshift/container_manager.rb
app/models/manageiq/providers/openshift/container_manager/container.rb
app/models/manageiq/providers/openshift/container_manager/container_group.rb
app/models/manageiq/providers/openshift/container_manager/container_node.rb
app/models/manageiq/providers/openshift/container_manager/event_parser.rb
app/models/manageiq/providers/openshift/container_manager_mixin.rb
app/models/manageiq/providers/openshift/monitoring_manager.rb
spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb

Depends on: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/410

Use inheritance not Mixins

---

app/models/manageiq/providers/openshift/inventory/collector.rb
app/models/manageiq/providers/openshift/inventory/collector/container_manager.rb
app/models/manageiq/providers/openshift/inventory/collector/container_manager/watch_notice.rb
app/models/manageiq/providers/openshift/inventory/parser.rb
app/models/manageiq/providers/openshift/inventory/parser/container_manager.rb
app/models/manageiq/providers/openshift/inventory/parser/container_manager/watch_notice.rb
app/models/manageiq/providers/openshift/inventory/persister.rb
app/models/manageiq/providers/openshift/inventory/persister/container_manager.rb
app/models/manageiq/providers/openshift/inventory/persister/container_manager/watch_notice.rb
spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb

Co-depends:
https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/423

Move Inventory WatchNotice under ContainerManager

---

.gitignore
config/secrets.defaults.yml
lib/manageiq/providers/openshift/engine.rb
spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
spec/spec_helper.rb

https://github.com/ManageIQ/manageiq/issues/21157

Pluggable provider secrets

---

systemd/manageiq-providers-openshift_container_manager_event_catcher@.service
systemd/manageiq-providers-openshift_container_manager_metrics_collector@.service
systemd/manageiq-providers-openshift_container_manager_refresh@.service
systemd/manageiq-providers-openshift_monitoring_manager_event_catcher@.service

part of https://github.com/ManageIQ/manageiq-rpm_build/pull/157
using manageiq properties and still running as root (but very close to switching over to manageiq user)

add properties files to systemd

---

systemd/manageiq-providers-openshift_container_manager_event_catcher@.service
systemd/manageiq-providers-openshift_container_manager_metrics_collector@.service
systemd/manageiq-providers-openshift_container_manager_refresh@.service
systemd/manageiq-providers-openshift_monitoring_manager_event_catcher@.service

run services as manageiq user

---

app/models/manageiq/providers/openshift/container_manager.rb
spec/models/manageiq/providers/openshift/container_manager/container_template_spec.rb

Part of:
* https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/453

Remove support for hawkular metrics

---

app/models/manageiq/providers/openshift/container_manager.rb
app/models/manageiq/providers/openshift/monitoring_manager.rb

part of https://github.com/ManageIQ/manageiq/pull/21573

converting supported_for_create to supports :create

---

app/models/manageiq/providers/openshift/container_manager.rb

Improve default credential verification

---

app/models/manageiq/providers/openshift/infra_manager/provision_workflow.rb
content/miq_dialogs/miq_provision_openshift_dialogs_template.yaml

Changes needed to support service catalog provisioning for the OSV provider
Depends on:
@miq-bot assign @agrare 
@miq-bot add_labels enhancement, radjabov/yes?
@miq-bot add_reviewer @agrare

Openshift Virtualization Service Catalog Support

---

app/models/manageiq/providers/openshift/infra_manager/event_catcher.rb
app/models/manageiq/providers/openshift/infra_manager/event_catcher/runner.rb
app/models/manageiq/providers/openshift/infra_manager/event_parser.rb
config/settings.yml
systemd/manageiq-providers-openshift_infra_manager_event_catcher.target
systemd/manageiq-providers-openshift_infra_manager_event_catcher@.service

Events collection for VMs on Openshift Virtualization
Depends on:
Needed for:
@miq-bot assign @agrare
@miq-bot add_label enhancement
@miq-bot add_reviewer @Fryguy, @agrare

Openshift Virtualization Events Capture

---

app/models/manageiq/providers/openshift/infra_manager/metrics_collector_worker.rb
app/models/manageiq/providers/openshift/infra_manager/metrics_collector_worker/runner.rb
config/settings.yml
systemd/manageiq-providers-openshift_infra_manager_metrics_collector.target
systemd/manageiq-providers-openshift_infra_manager_metrics_collector@.service

Metrics capture for OSV VMs
Depends on:
@miq-bot assign @agrare
@miq-bot add_label enhancement
@miq-bot add_reviewers @agrare, @Fryguy

Openshift Virtualization VM Metrics Capture

---

.github/CODEOWNERS

Related: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/549

Remove cben from CODEOWNERS

---

app/models/manageiq/providers/openshift/inventory.rb
app/models/manageiq/providers/openshift/inventory/parser/infra_manager/partial_target_refresh.rb

Follow-up to https://github.com/ManageIQ/manageiq-providers-kubevirt/pull/292
Ref: https://github.com/ManageIQ/manageiq-providers-kubevirt/pull/292#issuecomment-2847335862

Delete unused PartialTargetRefresh class for OSV

---

.gitignore
config/secrets.defaults.yml
lib/manageiq/providers/openshift/engine.rb
spec/config/secrets.defaults.yml
spec/models/manageiq/providers/openshift/container_manager/container_template_spec.rb
spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
spec/models/manageiq/providers/openshift/infra_manager/refresher_spec.rb
spec/spec_helper.rb

Switch to use VcrSecrets helper from core
