ManageIQ/manageiq-providers-openshift

- app/models/manageiq/providers/openshift/container_manager/refresh_parser.rb
- spec/models/manageiq/providers/openshift/container_manager/refresh_parser_spec.rb
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1441709
I dont know if this will solve the BZ completely since I cant really recreate the conditions in which this error was met.
for future reference the error logged was:
```
[----] E, [2017-04-11T15:35:03.125167 #12512:819138] ERROR -- : [NoMethodError]: undefined method `merge!' for nil:NilClass  Method:[rescue in block in refresh]
[----] E, [2017-04-11T15:35:03.125401 #12512:819138] ERROR -- : /var/www/miq/vmdb/app/models/manageiq/providers/openshift/container_manager/refresh_parser.rb:64:in `parse_project'
``` 
@moolitayer @cben Please review
cc @simon3z
> ignore projects without an underlying kubernetes namespace

- app/models/manageiq/providers/openshift/container_manager_mixin.rb
#We've been keeping 2 nearly-same functions in sync, especially painful after repo split:
- https://github.com/ManageIQ/manageiq-providers-kubernetes/blob/294010317/app/models/manageiq/providers/kubernetes/container_manager_mixin.rb#L22-L32
- https://github.com/ManageIQ/manageiq-providers-openshift/blob/1a25fff41f3/app/models/manageiq/providers/openshift/container_manager_mixin.rb#L34-L44
@zakiva @moolitayer Please review carefully.
- Minor change: now respects `options[:path]`, previously was forcing `/oapi`.
- Does `connect_client` still work right?  It sets `:service` which chooses `kubernetes_connect`/`openshift_connect`, but it also provides `:path`, `:version` which AFAICT covers both distinctions between them.  I suspect you previously passed `:service` here to work around forced …
> openshift_connect reuse kubernetes_connect

- manageiq-providers-openshift.gemspec
Previously, we got this dependency implicitly through manageiq,
kubeclient, etc.  Since we use this heavily in tests here, we should
state our reliance on this gem.
Needed for: ManageIQ/manageiq#15096
@simon3z please review
> Make recursive openstruct an explicit dependency

- app/models/manageiq/providers/openshift/container_manager/refresh_parser.rb
- spec/models/manageiq/providers/openshift/container_manager/refresh_parser_spec.rb
**Deiscription**
We currently insert a wrong place-holder value to the `ContainerImage#registered_on` field `:registered_on => Time.now.utc`
This PR remove this place-holder value from the Kubernetes provider, and insert the currect value in a new PR in the OpenShift provider.
Issue: https://github.com/ManageIQ/manageiq-providers-kubernetes/issues/17
Kubernetes PR: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/23
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1454329
> Move image registered_on field to openshift provider

- spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
Extracted from https://github.com/ManageIQ/manageiq/issues/14337.
Addresses the test points from ManageIQ/manageiq-providers-kubernetes#27 that I could cover
without rerecording the main casette.
(I'll want to rerecord at some point but don't want to block on it now...)
- SecurityContext is a Kubernetes concept, but we only have it in openshift casette, so tested here.
@zakiva @moolitayer Please review.
@miq-bot add-label test
> Add some missing refresher specs

- app/models/manageiq/providers/openshift/container_manager/refresh_parser.rb
See https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/48.
The `obj["table"][:namespace]` workaround is not needed since 2015,
and relies on a bug that is fixed in recursive-open-struct 1.0.3.
We happen to be pegged to =1.0.0 by kubeclient & image-inspector-client
(since at least capablanca) but would break soon.
Tested against both r-o-s 1.0.0 and 1.0.4.
@miq-bot add-label bug, technical debt
> Get rid of magic and soon buggy ["table"] RecursiveOpenStruct access

- app/models/manageiq/providers/openshift/container_manager/refresh_parser.rb
- spec/models/manageiq/providers/openshift/container_manager/refresh_parser_spec.rb
This is a bugfix for a problem mentioned here: https://github.com/ManageIQ/manageiq-providers-openshift/pull/30/files#r126438382
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1469482
cc @cben @moolitayer
> fix builds namespace matching

- app/models/manageiq/providers/openshift/container_manager/refresh_parser.rb
- spec/models/manageiq/providers/openshift/container_manager/refresh_parser_spec.rb
- spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
Openshift half of https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/46, same motivation & approach.
- Images only partially untangled — the real complication stayed in kubernetes `parse_container_image` reading and writing `data_index` for both images & registries :-(
I probably can live with that for initial graph refresh.
@miq-bot add-label refactoring
@enoodle @zeari @moolitayer @zakiva @yaacov Please review.
towards RFE: https://bugzilla.redhat.com/show_bug.cgi?id=1470021
> Separate data_index lookups from parsing

- app/models/manageiq/providers/openshift/container_manager.rb
- app/models/manageiq/providers/openshift/container_manager/orchestration_stack.rb
- app/models/manageiq/providers/openshift/container_manager/orchestration_stack/status.rb
- spec/models/manageiq/providers/openshift/container_manager/orchestration_stack_spec.rb
Add OrchestrationStack to track the provider created objects during provisioning.
Depends on https://github.com/ManageIQ/manageiq/pull/15429.
Depends on https://github.com/ManageIQ/manageiq/pull/15475.
https://www.pivotaltracker.com/story/show/134027413
> Add OrchestrationStack for container template provisioning.

- app/models/manageiq/providers/openshift/container_manager/container_image.rb
- app/models/manageiq/providers/openshift/container_manager/refresh_parser.rb
- spec/models/manageiq/providers/openshift/container_manager/refresh_parser_spec.rb
- spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
Addes openshift_container_images to the openshift provider.
Adding parsing for `ems_ref` for images originating from Openshift.
based on: https://github.com/ManageIQ/manageiq/pull/15386
> Adding openshift_container_images

- app/models/manageiq/providers/openshift/container_manager.rb
- app/models/manageiq/providers/openshift/monitoring_manager.rb
This is the third item of ManageIQ/manageiq-providers-kubernetes#39
Depends on: ManageIQ/manageiq#15354
> Add openshift monitoring manager

- spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
Spec test changes following https://github.com/ManageIQ/manageiq/pull/15393
@cben @moolitayer 
cc @simon3z
> Fix spec test for container and container_definition merger

- app/models/manageiq/providers/openshift/container_manager/refresh_parser.rb
- app/models/manageiq/providers/openshift/container_manager/refresher.rb
- config/settings.yml
- spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
RFE: https://bugzilla.redhat.com/show_bug.cgi?id=1470021
> Openshift graph refresh

- app/models/manageiq/providers/openshift/container_manager/refresh_parser.rb
- app/models/manageiq/providers/openshift/inventory.rb
- app/models/manageiq/providers/openshift/inventory/persister.rb
- app/models/manageiq/providers/openshift/inventory/persister/container_manager.rb
- spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
Depends on:
Add openshift persister and test also batch saver strategy
> Add openshift persister and test also batch saver strategy

- app/models/manageiq/providers/openshift/container_manager.rb
- app/models/manageiq/providers/openshift/container_manager/container_template.rb
- app/models/manageiq/providers/openshift/container_manager/refresh_parser.rb
- spec/models/manageiq/providers/openshift/container_manager/refresh_parser_spec.rb
- spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
Part of https://github.com/ManageIQ/manageiq/pull/15523.
Depends on https://github.com/ManageIQ/manageiq-schema/pull/35.
Depends on https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/79.
@miq-bot add_label refactoring
> Add ManageIQ::Providers::Openshift::ContainerManager::ContainerTemplate.

- app/models/manageiq/providers/openshift/container_manager/refresher.rb
Concrete benefit is separate `realtime_block` timing.
similar to
https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/82
I believe they're independent can be merged in either order.
@miq-bot add-label refactoring
> Refresher: Split collection from parsing methods

- app/models/manageiq/providers/openshift/container_manager.rb
- app/models/manageiq/providers/openshift/container_manager/options.rb
Using https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/45 for Openshift provider options.
This is required for using the options field with the Openshift provider as it adds the static description of the options (That is then being served through the API to the UI to present to the user when editing the options)
> Use the kubernetes options for Openshift

- app/models/manageiq/providers/openshift/container_manager/refresh_parser.rb
- config/settings.yml
- spec/models/manageiq/providers/openshift/container_manager/refresh_parser_spec.rb
- spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
openshift part of https://github.com/ManageIQ/manageiq/pull/14662 after repo split.  
**Depends on https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/11**
Strawman alternative/baseline for https://github.com/ManageIQ/manageiq/pull/14628.
Will allow to still get_container_images=true, but instead of saving metadata (labels etc) on all images openshift gave us, save it only for images that have been mentioned by pods.
cc @agrare @enoodle @zeari 
Added tests.  Recommend reviewing by commits (refactoring / new tests).
> Add ems_refresh.openshift.store_unused_images setting

- config/settings.yml
Same as https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/112, can be merged in any order.
There are some loose ends (notably tag mapping missing) but we want to get more testing from developers using it.
https://github.com/ManageIQ/manageiq-providers-kubernetes/issues/27
https://bugzilla.redhat.com/show_bug.cgi?id=1470021
> Enable graph refresh (batch strategy) by default

- app/models/manageiq/providers/openshift/container_manager/refresh_parser.rb
- spec/models/manageiq/providers/openshift/container_manager/refresh_parser_spec.rb
Depends on: https://github.com/ManageIQ/manageiq/pull/15406
@simon3z @moolitayer Please review
> Container Template: Parse object_labels

- spec/factories/openshift_template.rb
- spec/models/manageiq/providers/openshift/container_manager/container_template_spec.rb
- spec/vcr_cassettes/container_template.yml
Adding test for template instantiation with object labels and parameters. 
Depends on https://github.com/ManageIQ/manageiq/pull/15406, https://github.com/ManageIQ/manageiq/pull/15587
> Add Container Template Spec

- spec/vcr_cassettes/manageiq/providers/openshift/container_manager/refresher.yml
- spec/vcr_cassettes/manageiq/providers/openshift/container_manager/refresher_after_openshift_deletions.yml
- spec/vcr_cassettes/manageiq/providers/openshift/container_manager/refresher_before_openshift_deletions.yml
Followup to https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/121
Removed (by manual editing) `https://host.example.com:8443/api/v1/componentstatuses` requests from cassette to avoid "unused interactions" error.
@moolitayer @simon3z this should fix the build https://travis-ci.org/ManageIQ/manageiq-providers-openshift/builds
https://bugzilla.redhat.com/show_bug.cgi?id=1485431
> Drop Container Component Statuses

- app/models/manageiq/providers/openshift/monitoring_manager.rb
- app/models/manageiq/providers/openshift/monitoring_manager/event_catcher.rb
- app/models/manageiq/providers/openshift/monitoring_manager/event_catcher/runner.rb
- config/settings.yml
Based on: https://github.com/ManageIQ/manageiq-providers-openshift/pull/21
Fifth Item of https://github.com/ManageIQ/manageiq-providers-kubernetes/issues/39
> Prometheus alerts

- app/models/manageiq/providers/openshift/inventory/persister/container_manager.rb
- spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
Depends on:
Enable check metadata not deleted specs.
> Enable check metadata not deleted specs

- app/models/manageiq/providers/openshift/container_manager/inventory_collector_worker.rb
Vintage :TM: refresh for container providers doesn't reconnect container
images so having duplicate targets queued by the
InventoryCollectorWorker can lead to duplicate records.  For this reason
we want to disable the InventoryCollectorWorker if
`:inventory_object_refresh` is disabled.
> Don't start CollectorWorker if Graph Refresh disabled

- config/settings.yml
Due to the large payload size generated by the watch notices disable the collector worker by default until payloads can be moved to BinaryBlobs table
> Disable inventory collector worker by default

- app/models/manageiq/providers/openshift/container_manager/inventory_collector_worker.rb
The has_required_role? method wasn't calling the base
MiqWorker#has_required_role? leading to all workers in the zone running
the inventory collector.
Depends: ~~https://github.com/ManageIQ/manageiq/pull/16415~~
> Fix Inventory Collector has_required_role?

- app/models/manageiq/providers/openshift/container_manager/refresh_parser.rb
- spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
Covers routes, builds.
Images & templates tag mapping out of scope, they've never worked in old refresh either, will fix separately.
Depends on:
to define Tag.controlled_by_mapping scope
Overview/plan issue: https://github.com/ManageIQ/manageiq-providers-kubernetes/issues/126
@miq-bot add-label enhancement, gaprindashvili/yes
https://bugzilla.redhat.com/show_bug.cgi?id=1470021
> Tag mapping in graph refresh

- app/models/manageiq/providers/openshift/container_manager.rb
- spec/models/manageiq/providers/openshift/container_manager_spec.rb
For Service Catalogs each provider manager needs to provide the catalog types it supports
Needed for https://github.com/ManageIQ/manageiq/pull/16559
> Added supported_catalog_types

- spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
A test for https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/89.
```
expected collection contained:  [["dns", "UDP", 53], ["dns-tcp", "TCP", 53], ["https", "TCP", 443]]
actual collection contained:    [["dns-tcp", "TCP", 53], ["https", "TCP", 443]]
```
passes with that PR.
Already passes in graph refresh, will ensure https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/212 and https://github.com/ManageIQ/manageiq-schema/pull/19 don't break it.
@Ladas please review.
> Add test for service ports with same number different protocol

- app/models/manageiq/providers/openshift/container_manager/refresh_parser.rb
Depends on:
We need to use existing relation to project so we build valid query,
otherwise the targeted specs fails.
> We need to use existing relation to project so we build valid query

- spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
- spec/models/manageiq/providers/openshift/container_manager/targeted_refresh/targeted_refresh_spec.rb
We hope to only use the fastest {:saver_strategy => :batch, :use_ar_object => false} in production, but testing all helps expose bugs in refresh...
Same as https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/235, can be merged independently.
> Test :batch strategy with and without :use_ar_object

- spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
Comparing times with strings no longer works after have_attributes
extension was removed in https://github.com/ManageIQ/manageiq/pull/17021
> Fix comparison of TimeWithZone and string

- spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
There are category/entry Tags, and category/entry Classifications.
```
.parent
category Classification "cat"   <----------   entry Classification "ent"
|^                ^                        |^
.tag||.classification  \_______________    .tag||.classification
v|                     .category   \       v|
category Tag /managed/cat                     entry Tag /managed/cat/ent
```
`.category` is supposed to get the "uncle", the category Classification from an *entry* Tag.
`mapping.tag` is a category Tag (for any-value mappings which are the kind we use).
Currently `.category` on a category Tag ("/managed/cat") happens to work same as `.classification`, but it's ill-defined and will stop working after https://github.com/ManageIQ/manageiq/pull/17418.
@miq-bot add-label test, technical …
> mapping.tag is a category Tag, calling .category is ill-defined

- config/settings.yml
- spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
- spec/models/manageiq/providers/openshift/container_manager/targeted_refresh/targeted_refresh_spec.rb
Symbols in configuration values are problematic because Symbols do not roundtrip through JSON.  Since the API now exposes Settings, it's not possible to set Symbols as values.  The saver_strategy was fixed in ManageIQ/manageiq#17168 to support String values, and the next step is to remove all Symbols from the Settings.
ManageIQ/manageiq#17201
https://bugzilla.redhat.com/show_bug.cgi?id=1558031
@miq-bot add-labels bug, gaprindashvili/yes
@Fryguy @moolitayer please review.  This is similar to https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/246.
> Change saver_strategy value to String

- spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
ContainerImage is not destroyed by ContainerImageRegistry, which fixes pending specs
Cc @cben, @Ladas
> ContainerImage archivation

- app/models/manageiq/providers/openshift/inventory/persister.rb
- app/models/manageiq/providers/openshift/inventory/persister/container_manager.rb
- app/models/manageiq/providers/openshift/inventory/persister/target_collection.rb
**Issue**: https://github.com/ManageIQ/manageiq/issues/17396
**dependent**: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/266
New Interface for definition/creating InventoryCollection from persister.
Using add_collection() instead of add_inventory_collection() to build collections.
Builder classes are defined on core project, provider specific InventoryCollections specified in concerns
> Persister: InventoryCollection building through add_collection()

- spec/models/manageiq/providers/openshift/container_manager/refresher_inventory_object_spec.rb
This was merged after the PR that renamed all ManagerRefresh::Inventory
to ManageIQ::Providers::Inventory
> Fix a reference to ManagerRefresh::Inventory

- spec/factories/ext_management_system.rb
- spec/models/manageiq/providers/openshift/container_manager/container_template_spec.rb
- spec/models/manageiq/providers/openshift/container_manager/refresher_inventory_object_spec.rb
- spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
- spec/models/manageiq/providers/openshift/container_manager/targeted_refresh/targeted_refresh_spec.rb
A number of specs were failing due to a missing zone and a new MiqQueue validation
> Fix specs failing on a missing zone

- spec/vcr_cassettes/container_template.yml
A recent change in the `manageiq-provider-kubernetes` project changed the connection logic, so that the API discovery is called when the connection is created by the provider:
> Discover API endpoint in kubernetes_connection
> https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/288
This affects the test that checks instantiation of templates, as there are now two requests to the discovery endpoint: one when the provider is created, and another one when the templates is instantiated. To account for this the VCR cassette needs to be updated.
> Fix VCR cassete for container template instantiation

- spec/models/manageiq/providers/openshift/container_manager/refresher_inventory_object_spec.rb
https://github.com/abonas/kubeclient/pull/299 removed the
Kubeclient::Common::WatchNotice class, now watches just return
Kubeclient::Resource objects.
> Kubeclient v3.1.0 removed Common::WatchClient

- app/models/manageiq/providers/openshift/inventory/persister/container_manager.rb
The shared_options were duplicated from the base persister
> Remove duplicated persister shared_options

- app/models/manageiq/providers/openshift/container_manager/refresh_parser.rb
- spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
Disable the ability to switch the refresh type and only support graph
refresh.
Related to: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/340
> Only allow for graph refresh

- README.md
We no longer do per-plugin translations, we don't need to mention zanata in README.
@miq-bot add_label cleanup
> Remove from README

- app/models/manageiq/providers/openshift/container_manager.rb
- app/models/manageiq/providers/openshift/container_manager/inventory_collector_worker.rb
- app/models/manageiq/providers/openshift/container_manager/inventory_collector_worker/runner.rb
- config/settings.yml
The InventoryCollectorWorker was an experimental streaming refresh
worker for kubernetes/openshift but was never used.
> Remove unused InventoryCollectorWorker

- app/models/manageiq/providers/openshift/container_manager.rb
Use the params_for_create and verify_credential methods from ContainerManagerMixin in kubernetes, just need to define the default_port
Depends on: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/341
https://github.com/ManageIQ/manageiq/issues/18818
> Add default_port needed for params_for_create

- app/models/manageiq/providers/openshift/container_manager.rb
- config/settings.yml
Remove inventory_object_refresh from settings as part of the effort to remove the old legacy EmsRefresh and save_inventory refresh code.
> Remove settings inventory refresh

- app/models/manageiq/providers/openshift/container_manager/container_template.rb
The container template operations are openshift specific and should live in the openshift repo.
This was originally moved out of core here https://github.com/ManageIQ/manageiq/pull/15523
Dependent: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/365
> Move container_template operations into Openshift

- app/models/manageiq/providers/openshift/container_manager/container_template.rb
- app/models/manageiq/providers/openshift/container_manager_mixin.rb
Follow-up to https://github.com/ManageIQ/manageiq-providers-openshift/issues/139#issuecomment-611938172
This most likely wasn't working for a long time, `obj.symbolize_keys[:metadata][:namespace]` was failing because it was at `obj[:metadata]["namespace"]`
> Fix instantiate container template

- app/models/manageiq/providers/openshift/container_manager.rb
Fix `#create_project` on openshift 4 by passing in the API Group
Follow-up to https://github.com/ManageIQ/manageiq-providers-openshift/issues/139
> Pass api_group when creating a project

- app/models/manageiq/providers/openshift/container_manager_mixin.rb
ContainerRoutes should belong to the EMS for all ContainerManagers not just Openshift
Depends on: https://github.com/ManageIQ/manageiq/pull/20126
Cross Repo Test: https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/118
> Container routes always belong to the EMS

- app/models/manageiq/providers/openshift/container_manager_mixin.rb
Move this method out of the UI and into the provider
https://github.com/ManageIQ/manageiq-ui-classic/pull/7043
> Add a method to detect the metrics service hostname

- app/models/manageiq/providers/openshift/container_manager_mixin.rb
This service isn't the same prometheus alert buffer that exposes the /topic/alerts API that we need for the MonitoringManager.
It might be possible to configure OCPv4 with Prometheus Alert Buffer but it isn't default so we shouldn't auto-detect it.
Fixes https://github.com/ManageIQ/manageiq-providers-openshift/issues/177
> V4 openshift-monitoring/alertmanager-main isn't the PrometheusAlertBuffer

- config/settings.yml
https://github.com/ManageIQ/manageiq-providers-openshift/pull/169 backported cleanly but we wanted to disable this by default (https://github.com/ManageIQ/manageiq-providers-kubernetes/commit/a11a3a86f3600411126017c7775eb15470b57385 on the kubernetes side)
> [JANSA] Disable streaming refresh by default

- app/models/manageiq/providers/openshift/container_manager.rb
- app/models/manageiq/providers/openshift/container_manager/container_template.rb
- spec/models/manageiq/providers/openshift/container_manager_spec.rb
Add methods that can be easily overridden by an initializer to the 
container templates supports :instantiation check.
> Add methods that can be overridden easily to ContainerTemplate

- app/models/manageiq/providers/openshift/container_manager.rb
- app/models/manageiq/providers/openshift/container_manager/container.rb
- app/models/manageiq/providers/openshift/container_manager/container_group.rb
- app/models/manageiq/providers/openshift/container_manager/container_node.rb
- app/models/manageiq/providers/openshift/monitoring_manager.rb
> Subclassed provider classes should mark the parent as a leaf class 

- app/models/manageiq/providers/openshift/container_manager.rb
This causes refresh to fail with `expected service_instances to be found subclassed as ManageIQ::Providers::Openshift::ContainerManager::ServiceInstance, but instead found ServiceInstance`
> Add missing require_nested Service*

- app/models/manageiq/providers/openshift/inventory/parser/openshift_parser_mixin.rb
The lazy_find_by method is no different from the lazy_find method now and will be removed in an upcoming inventory_refresh release
> Replace lazy_find_by with simple lazy_find

- app/models/manageiq/providers/openshift/inventory/parser/openshift_parser_mixin.rb
- manageiq-providers-openshift.gemspec
parse_container_image accepts kwargs, ruby 3 requires it be explicit. Loosen recursive-open-struct to allow ruby 3 supported kubeclient.
> Support ruby 3

- app/models/manageiq/providers/openshift/container_manager/metrics_collector_worker.rb
This worker wasn't inheriting from Kubernetes' MetricsCollectorWorker class thus didn't pull in the code to not start up if there are no Openshift providers with a metrics endpoint.
Depends:
> Fix MetricsCollectorWorker running with invalid creds

- app/models/manageiq/providers/openshift/container_manager.rb
The 8443 port was the default port for Openshift v3, on v4 Openshift moved to using API Groups which means it has the same port for all API endpoints.
> Openshift v4 has same default port as k8s

- app/models/manageiq/providers/openshift/container_manager.rb
- spec/models/manageiq/providers/openshift/container_manager_spec.rb
- spec/vcr_cassettes/container_template.yml
We were using `/apis/apps.openshift.io/v1` as the API group to check for ocpv4, but ocpv3 actually responds to this API group and v3 clusters were passing.
> Fail verify_credentials for Openshift v3 clusters

- lib/manageiq-providers-openshift.rb
- lib/manageiq/providers/openshift.rb
- spec/spec_helper.rb
Adopt convention already supported by bundler and required by zeitwerk so we don't need to tell zeitwerk to ignore this lib/gem-name.rb file
> Drop lib/gem-name.rb in favor of lib/gem/name.rb

- app/models/manageiq/providers/openshift/container_manager.rb
- app/models/manageiq/providers/openshift/container_manager/event_catcher.rb
- app/models/manageiq/providers/openshift/container_manager/metrics_collector_worker.rb
- app/models/manageiq/providers/openshift/container_manager/orchestration_stack.rb
- app/models/manageiq/providers/openshift/container_manager/refresh_worker.rb
- app/models/manageiq/providers/openshift/inventory.rb
- app/models/manageiq/providers/openshift/inventory/collector.rb
- app/models/manageiq/providers/openshift/inventory/collector/container_manager.rb
- app/models/manageiq/providers/openshift/inventory/parser.rb
- app/models/manageiq/providers/openshift/inventory/parser/container_manager.rb
- app/models/manageiq/providers/openshift/inventory/persister.rb
- app/models/manageiq/providers/openshift/inventory/persister/container_manager.rb
- app/models/manageiq/providers/openshift/monitoring_manager.rb
- app/models/manageiq/providers/openshift/monitoring_manager/event_catcher.rb
Zeitwerk completely removes the need for these methods. See also: https://github.com/ManageIQ/manageiq/pull/22854
> Drop require_nested 

- app/models/manageiq/providers/openshift/container_manager/container_template.rb
@agrare I see that we added `instantiate_supported?` in c7213d39
Do we still need that?
I don't see it defined or extended anywhere.
Alternatively, can we just use `instantiate_unsupported_reason` and drop the `instantiate_supported?` ?
**ANSWER:** punting for now
---
part of:
- https://github.com/ManageIQ/manageiq/pull/22898
Deprecating `unsupported_reason_add`. Returning the string instead
Note, these are all the same:
```ruby
unsupported_reason_add(:feature, unsupported_reason(:feature2)) unless supports_feature2?
unsupported_reason_add(:feature, unsupported_reason(:feature2)) unless supports?(:feature2)
unsupported_reason(:feature2) unless supports?(:feature2)
unsupported_reason(:feature2)
```
> drop use of unsupported_reason_add

- app/models/manageiq/providers/openshift/inventory/parser/openshift_parser_mixin.rb
- spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
Relevant PRs:
Providers-Kubernetes: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/530
UI-Classic: https://github.com/ManageIQ/manageiq-ui-classic/pull/9214
Core ManageIQ: https://github.com/ManageIQ/manageiq/pull/23074
Cross-Repo Tests:
https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/879 
All passing except for known failing test cases in core ManageIQ
> Add annotations to custom attributes on summary pages for routes and templates

- app/models/manageiq/providers/openshift/infra_manager/refresh_memory.rb
```
An unhandled error has occurred: uninitialized constant ManageIQ::Providers::Openshift::RefreshMemory
@memory ||= provider_class::RefreshMemory.new
^^^^^^^^^^^^^^^
app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb:75:in `memory'
app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb:194:in `block in start_watches'
```
Depends on:
> Fix full refresh error when running a RefreshWorker

- app/models/manageiq/providers/openshift/infra_manager/refresh_worker/runner.rb
```
[----] E, [2024-09-25T12:54:33.983014#1039874:c23a8] ERROR -- evm: MIQ(ManageIQ::Providers::Openshift::InfraManager::RefreshWorker::Runner#partial_refresh) Partial refresh failed.
[----] E, [2024-09-25T12:54:33.985633#1039874:c23a8] ERROR -- evm: [NoMethodError]: undefined method `nodes=' for #<ManageIQ::Providers::Openshift::Inventory::Collector:0x00007faf8d8dd288 @    manager=#<ManageIQ::Providers::Openshift::InfraManager id: 6, name: "crc Virtualization Manager", created_on: "2024-09-09 20:33:10.220755000 +0000", updated_on: "2024-09-25 16:53:23.023870210 +0000", guid: "482ceee5-e5cf-402e-80f6-cc5c78cbd0e6", zone_id: 2, type: "ManageIQ::Providers::Openshift::InfraManager", api_version: nil, uid_ems: nil, host_default_vnc_port_start: nil,         host_default_vnc_port_end: nil, …
```
> Fix refresh worker partial refresh error

- manageiq-providers-openshift.gemspec
Fog-kubevirt fails to marshal_dump a recursive-open-struct because of a breaking change in the return value in version 1.3.0.
Likely introduced by https://github.com/aetherknight/recursive-open-struct/pull/72
Fog-kubevirt issue https://github.com/fog/fog-kubevirt/issues/161
> Lock down recursive-open-struct to 1.2.2

- app/models/manageiq/providers/openshift/infra_manager.rb
- config/settings.yml
Reasoning here: https://github.com/ManageIQ/manageiq-providers-azure/pull/564#issuecomment-2445034651
@miq-bot assign @agrare
@miq-bot add_label bug, radjabov/yes?
@miq-bot add_reviewer @agrare
> Delegate refresh_ems class method to parent container manager

- app/models/manageiq/providers/openshift/container_manager.rb
Fix an issue when editing an Openshift ContainerManager where the Virtualization Type shows as Disabled even though there is an InfraManager already created.
Here is what the ContainerManager Endpoint roles look like:
```
>> openshift.endpoints.pluck(:role)
=> ["default", "prometheus", "kubevirt"]
```
So it was looking for an "openshift" role and there wasn't one.
Before:
After:
> Fix OSV DDF form pivot value

- app/models/manageiq/providers/openshift/infra_manager/connection.rb
This wass a subclass of the Kubevirt Connection class which abstracted the API groups away from the caller but presented more complications than it was worth when dealing with kubeclient + kubevirt connections.
Deleted by https://github.com/ManageIQ/manageiq-providers-kubevirt/pull/276
> Delete unused InfraManager::Connection subclass
